language: cpp

sudo: false

os:
  -linux

compiler:
  -clang

install: true

add_ons: {
  apt: {
    sources: [
      "ubuntu-toolchain-r-test",
      "llvm-toolchain-trusty"
    ],
    packages: [
      "clang",
    ]
  }
}

script: scan-build g++ test.cpp
  
